baseURL = "https://aurore.rbind.io/"
languageCode = "en-us"
title = "aurore"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Aurore Paligot - All rights reserved"
enableEmoji = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  #logo = "/images/logo.png"
  description ="a data journey"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Aurore Paligot"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/flow.png"
  #title = "John Doe"
  #subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''

##### Hello, I'm Aurore. 
##### I create stuff with data. 
##### Welcome to my blog.
'''
  alertbar = false

[params.social]
  github = "<username>"
  linkedin = "<username>"
  #xing = "<username>"
  #medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 200
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "projects"
    weight = 200
    identifier = "projects"
    url = "/project/"
[[menu.main]]
    name = "bonjour"
    identifier = "landing"
    weight = 300
    url = "/"
[[menu.main]]
    name = "about me"
    identifier = "imprint"
    weight = 300
    url = "/static/imprint"
