---
title: (Insta)gram the dam. A portrait of Amsterdam Urban Beaches
author: Aurore Paligot
date: '2020-10-24'
slug: instagram-the-dam
categories:
  - Project
tags:
  - Digital Humanities
  - Text Mining
  - Smart City
  - Social Media
publishdate: '2020-10-24T19:32:11+02:00'
comments: yes
---
What do an architect and a linguist do when they work together? 

Tom van Arman and I started to explore the possibility of using Social Media Data as an Urban Design Tool. These interactive dashboards, based on data extracted from Instagram, invite us to observe the spaces we inhabit through social media. This data testify to the activity of communities (citizens, tourists, loiterers or workers) present online and offline and participate in the construction of our representations of urban spaces. What is the place of these representations in the implementation of smart cities projects? What are the potential points of friction between competing representations of shared spaces? These data aim to put the citizen at the heart of smart city projects and to open a dialogue with the public.

In this first series, we collected data from four urban beaches in Amsterdam: Marineterrein, Pllek, Westerdok and Sloterplas. The first dashboard presents the evolution of the popularity of these places according to the Instagram interactions associated with them. The Marineterrein, in yellow, is not only our workplace and a Living Lab, but also a recreational site in Amsterdam that has secretly become one of the most popular beaches in our hot summers. Of course, this popularity on the voorwerf is also reflected online and on Intsagram!All three tables are interactive. Move your mouse over the data to reveal their content.

## `#`InstagramtheDam

In connection with this project, I created an instagram account called insta.gramthedam linked to the hashtag #instagramthedam (itself derived from the popular #gramthedam). Thats's the place where I will present in more details the data related to this portrait of the beaches of Amsterdam while leaving the door open for the creation of other series in the future.

My open question to you is: Do you recognize your favorite Amsterdam's spots through the lenses of Social Media?