---
title: The actual dangers of AI - by Janelle Shane for TED
author: Aurore Paligot
date: '2020-11-12'
slug: the-actual-dangers-of-AI
categories:
  - Reference
  - Sharing Ideas
tags:
  - AI
  - visual recognition
  - data
publishdate: '2020-11-12T00:23:20+01:00'
comments: yes
draft: true
---
### A cool AI video introduction

I absolutely love this neat presentation about what are the actual dangers of AI by Janelle Shane, where she underlines two fundamentals aspects of the issue. 



The first aspect is

"The problem with AI is not that it's going to rebel against us. It's that it's going to do exactly what we ask it to do. So the trick of working with AI becomes how to set up the problem so that it actually does what we want.(...) It's really easy to give AI the wrong problem to solve and often we don't realize that until something has actually gone wrong."

The second aspect is 

"It's entire world is the data that I gave it. It doesn't know about anything else. It is through the data that we often accidentally tell AI to do the wrong thing.(...) When we're working with AI, it's up to us to avoid problems."

[Ted - The danger of AI is weirder than you think - 14 November 2019](https://www.youtube.com/watch?v=OhCzX0iLnOc)